---

- name: Simple Rusty App POC
  hosts: app

  vars:
    rustup: rustup.sh
    app_db: mydb
    db_user: 'vagrant'
    db_pass: '123456'

  roles:
    - role: pgsql-client
      vars:
        db_host: '{{ db }}'
        db_name: '{{ app_db }}'
        # db_pass: '{{ db_pass }}'
        # db_user: '{{ db_user }}'
    - role: zabbix-client

  tasks:
    - name: Download rustup
      get_url:
        url: https://sh.rustup.rs
        dest: "/home/vagrant/{{ rustup }}"

    - name: Install rust
      command: sh ./{{ rustup }} -y
      args:
        creates: .cargo/bin/rustc

    - name: Install pre-pre-reqs (epel/pgsql)
      # redis
      package:
        #name: [ 'epel-release', 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm' ]
        name: epel-release
        state: present
      become: true

    - name: Install pre-reqs
      package:
        name: [ 'redis', 'git', 'gcc', 'openssl-devel' ]
        state: present
      become: true
      notify: Start Services


    # Start Services, if required
    - meta: flush_handlers

    - name: Git (hee hee) the rusty app
      git:
        repo: https://github.com/jhriv/rust-web-demo.git
        # forked from https://github.com/hikelee/rust-web-demo
        dest: rust-web-demo
        update: false
        # so we can configure it below, and remain idempotent

    - name: Fix database connector
      lineinfile:
        path: rust-web-demo/web-root/config/web.conf
        regexp: '(\s*{{ item.key }}\s*=)"[^"]*"(.*)'
        line: '\1"{{ item.value }}"\2'
        backrefs: true
      no_log: true
      loop:
        - { key: 'host',      value: '{{ db }}'      }
        - { key: 'db_name',   value: '{{ app_db }}'  }
        - { key: 'user_name', value: '{{ db_user }}' }
        - { key: 'password',  value: '{{ db_pass }}' }
      tags: try

    - name: Init the database
      command: >
        psql --file=/home/vagrant/rust-web-demo/web-root/sql/init.sql -d postgres://{{ db_user }}:{{db_pass}}@{{ db }}/{{ app_db }}
      register: p_out
      changed_when: p_out.stderr_lines | length == 0

    - name: Compile our happy appy
      command: cargo build
      args:
        chdir: rust-web-demo
        creates: target/debug/app
      environment:
        PATH: /home/vagrant/.cargo/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin

    - name: Install Systemd Service File
      template:
        src: "{{ item }}.j2"
        dest: /etc/systemd/system/{{ item }}
      become: true
      loop:
        - "rust-web-demo.service"
      notify: Systemd Reload

    # Reload systemd, if required
    - meta: flush_handlers

    - name: Start the app
      service:
        name: rust-web-demo
        enabled: true
        state: started
      become: true

  handlers:
    - name: Start Services
      service:
        name: '{{ item }}'
        state: started
        enabled: true
      become: true
      loop:
        - redis

    - name: Restart PostgreSQL
      service:
        name: postgresql-{{ pgsql_major_version }}
        state: restarted
      become: true
      delegate_to: '{{ db }}'

    - name: Systemd Reload
      command: systemctl daemon-reload
      become: true
