---

- name: Add Zabbix Repository
  package:
    name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
    #name: https://repo.zabbix.com/zabbix/4.4/rhel/7/x86_64/zabbix-release-4.4-1.el7.noarch.rpm
    state: present
  become: true

- name: Install Zabbix Agent
  package:
    name: [ 'zabbix-agent' ]
    state: present
  become: true

# If we need to run the agent as root:
# /etc/systemd/system/zabbix-agent.service.d/override.conf
# [Service]
# User=root
# Group=root

- name: Configure Agent
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    line: '{{ item.key }}={{ item.value }}'
    regexp: '{{ item.key }}='
    state: present
  become: true
  loop:
    - { key: 'Server', value: '{{ zabbix_server }}' }
    - { key: 'ServerActive', value: '{{ zabbix_server }}' }
    - { key: 'Hostname', value: '{{ zabbix_client_name | default ( inventory_hostname) }}' }
    # - { key: '', value: '' }
    # - { key: '', value: '' }

- name: Enable Agent
  service:
    name: zabbix-agent
    state: started
    enabled: true
  become: true
